name: actions
run-name: ${{ github.actor }} is running TPLab04
on: [push]
jobs:
  container-job:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /Users/mihailerosenko/z1qnezt/workspace/projects/lab04
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
      - name: Test project
        run: ./.github/workflows/test.sh
